services:
  rp:
    image: "traefik:v3.0"
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.rp.rule=Host(`rp.docker.localhost`)"
  drupal:
    image: "aviumlabs/drupal:latest-bookworm" 
    restart: always
    ports:
      - "8090:80"
    volumes:
      - drupal_data:/var/www/html
      - ./src:/opt/drupal/web/modules/custom
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.http.routers.drupal.rule=Host(`drupal.docker.localhost`)"
  db:
    env_file: 
      - path: ./.env 
        required: true
    image: "postgres:16.3-alpine3.20"
    restart: always
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
volumes:
  drupal_data:
  db_data:

secrets:
  postgres_password:
    file: ./.secret_db
