services:
  www: 
    image: "aviumlabs/nginx-drupal-proxy:latest-alpine"
    restart: unless-stopped
    volumes:
      - www_modules:/var/www/html/modules
      - www_profiles:/var/www/html/profiles
      - www_themes:/var/www/html/themes 
      - www_sites:/var/www/html/sites
    ports:
      - 8080:80
    depends_on:
      - drupal
    networks:
      - external 
  drupal:
    image: "aviumlabs/drupal:latest-alpine" 
    restart: unless-stopped 
    volumes:
      - www_modules:/var/www/html/modules
      - www_profiles:/var/www/html/profiles
      - www_themes:/var/www/html/themes 
      - www_sites:/var/www/html/sites
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - external
  db:
    env_file: 
      - path: ./.env 
        required: true
    image: "postgres:16.2-alpine3.19"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password

volumes:
  db_data:
  www_modules:
  www_profiles:
  www_themes:
  www_sites:

secrets:
  postgres_password:
    file: ./.secret_db

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
