services:
  drupal:
    image: "aviumlabs/drupal:latest-bookworm" 
    restart: unless-stopped
    volumes:
      - drupal_data:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - external
  db:
    env_file: 
      - path: ./.env 
        required: true
    image: "postgres:16.2-alpine3.19"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password

volumes:
  drupal_data:
  db_data:

secrets:
  postgres_password:
    file: ./.secret_db

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
