apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: hostpath
